# Generated by Django 4.2.23 on 2025-08-19 21:25

from django.db import migrations

def add_resume_review_activity(apps, schema_editor):
    Activity = apps.get_model('core', 'Activity')
    
    # Create resume review request activity if it doesn't exist
    activity, created = Activity.objects.get_or_create(
        activity_type='resume_review_request',
        defaults={
            'name': 'Resume Review Request',
            'points_value': 20,
            'description': 'Request for professional resume review and feedback',
            'is_active': True,
        }
    )
    
    if created:
        print(f"Created activity: {activity.name}")
    else:
        print(f"Activity already exists: {activity.name}")

def remove_resume_review_activity(apps, schema_editor):
    Activity = apps.get_model('core', 'Activity')
    Activity.objects.filter(activity_type='resume_review_request').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_resume_review_models'),
    ]

    operations = [
        migrations.RunPython(add_resume_review_activity, remove_resume_review_activity),
    ]
