# Generated by Django 4.2.23 on 2025-08-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_resume_review_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='media_consent',
            field=models.BooleanField(blank=True, default=None, help_text="User's consent to be featured in EngageHub media materials", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='media_consent_date',
            field=models.DateTimeField(blank=True, help_text='Date when consent decision was made', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='media_consent_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address when consent decision was made', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='media_consent_user_agent',
            field=models.TextField(blank=True, help_text='User agent string when consent decision was made', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed the onboarding flow'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed_date',
            field=models.DateTimeField(blank=True, help_text='Date when onboarding was completed', null=True),
        ),
    ]
