# Generated by Django 4.2.23 on 2025-08-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_scheduling_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_username_unverified",
            field=models.CharField(
                blank=True,
                help_text="Discord username provided during registration (unverified)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="discord_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the Discord account has been verified via bot",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="discord_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When Discord verification was completed",
                null=True,
            ),
        ),
    ]
