# Generated by Django 4.2.23 on 2025-08-26 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_discord_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('engagement', 'Community Engagement'), ('professional', 'Professional Development'), ('social', 'Social Media'), ('events', 'Events & Networking'), ('content', 'Content Creation'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='incentive',
            name='category',
            field=models.CharField(choices=[('merchandise', 'Merchandise'), ('gift_cards', 'Gift Cards'), ('experiences', 'Experiences'), ('services', 'Services'), ('digital', 'Digital Rewards'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='incentive',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to reward image', null=True),
        ),
        migrations.AddField(
            model_name='incentive',
            name='stock_available',
            field=models.IntegerField(default=0, help_text='Number of items available'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='delivery_details',
            field=models.JSONField(default=dict, help_text='Delivery address and contact info'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redemption',
            name='tracking_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.JSONField(default=dict, help_text='Email notification preferences')),
                ('privacy_settings', models.JSONField(default=dict, help_text='Privacy and display preferences')),
                ('display_preferences', models.JSONField(default=dict, help_text='UI display preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
    ]
