# Generated by Django 4.2.23 on 2025-08-26 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_activity_category_incentive_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointslog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
