# Generated by Django 4.2.23 on 2025-09-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20250902_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name for UI (defaults to username if not set)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Expected graduation year', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, help_text="User's major/field of study", max_length=100, null=True),
        ),
    ]
