# Generated by Django 4.2.23 on 2025-09-13 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tech', 'Tech'), ('consulting', 'Consulting'), ('finance', 'Finance')], max_length=20, unique=True)),
                ('display_name', models.CharField(help_text='Display name for UI', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the track')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tracks',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Career track for students', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.track'),
        ),
    ]
