# Generated by Django 4.2.23 on 2025-09-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_resourcesubmission'),
        ('core', '0014_add_track_system'),
    ]

    operations = [
    ]
