# Generated by Django 4.2.23 on 2025-09-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_0010_resourcesubmission_0014_add_track_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'ordering': ['-updated_at']},
        ),
    ]
