# Generated by Django 4.2.23 on 2025-09-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_userpreferences_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resourcesubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='idx_resource_status_submitted'),
        ),
        migrations.AddIndex(
            model_name='resourcesubmission',
            index=models.Index(fields=['user', 'status'], name='idx_resource_user_status'),
        ),
    ]
