# Generated by Django 4.2.23 on 2025-09-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_redemptionnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentive',
            name='tier',
            field=models.CharField(
                choices=[
                    ('tier1', 'Tier 1 (Foundational Rewards)'),
                    ('tier2', 'Tier 2 (Premium Resources & Scaled Access)'),
                    ('tier3', 'Tier 3 (High-Value Human Interaction)'),
                    ('tier4', 'Tier 4 (Elite & Bespoke Rewards)'),
                ],
                default='tier1',
                max_length=10
            ),
        ),
    ]
