# Generated by Django 4.2.23 on 2025-09-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_new_submission_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsubmission",
            name="description",
        ),
        migrations.RemoveField(
            model_name="eventsubmission",
            name="event_name",
        ),
        migrations.RemoveField(
            model_name="linkedinsubmission",
            name="update_description",
        ),
        migrations.AddField(
            model_name="eventsubmission",
            name="event_details",
            field=models.TextField(
                blank=True, default="User claims to have attended an event"
            ),
        ),
        migrations.AddField(
            model_name="linkedinsubmission",
            name="linkedin_url",
            field=models.TextField(
                blank=True, default="User claims to have posted a LinkedIn update"
            ),
        ),
    ]
